settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
schema:
- name: res-sys
  path: /home/tmtx/projects/res-sys
  commands:
    fmt:
      status: true
    test:
      status: true
    install:
      status: true
      method: go build -o build/res-sys github.com/tmtx/res-sys/cmd/all/...
    run:
      status: true
      method: build/res-sys
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
