settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
schema:
- name: erp
  path: /home/tmtx/projects/erp
  commands:
    fmt:
      status: true
    test:
      status: true
    install:
      status: true
      method: go build -o /home/tmtx/go/bin/erp github.com/tmtx/erp/cmd/all/...
    run:
      status: true
      method: /home/tmtx/go/bin/erp
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
