version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27018:27017
    networks:
      - app-tier
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
  app:
    build: .
    ports:
      - 8081:8080
    depends_on:
      - "mongo"
      - "redis"
    networks:
      - app-tier
